### ISSUE TITLE
TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by QiuleiWang** [boolangery/py-lua-parser#22]
self.data = [ord(c) for c in self.strdata]
TypeError: ord() expected string of length 1, but int found

**Comment by merwok** [comment]
The report would be more useful with the full error message, including file and location!

This could be a Python 2 / 3 conversion issue; if `strdata` is bytes, then it’s already a sequence of bytes, no need for `ord`.

**Comment by QiuleiWang** [comment]
I solved the problem because my parameter type is wrong,
 ast.parse(str(lua_content, encoding = "utf8"))
