### ISSUE TITLE
Rendering Some Lua Tables False

### ISSUE THREAD

**Issue by Asteriva** [boolangery/py-lua-parser#26]
**Example code:**
```lua 
local Table = {"a", "b", "c"};
```

**I have used ast.to_lua_source for turning the ast into a lua code**
**The output i got:**
```lua
local Table = {
    1 = "a",
    2 = "b",
    3 = "c",
}
;
```

**What it should be:**
```lua
local Table = {
    [1] = "a",
    [2] = "b",
    [3] = "c",
}
;
```

**Used python code:**
```py
from luaparser import ast

src = """
local Table = {"a", "b", "c"};
"""

tree = ast.parse(src)
print(ast.to_lua_source(tree))
```

**Comment by MikeMihailov** [comment]
The same problem

**Comment by uniquadev** [comment]
I made a fix for that I'll soon pull it

> **Example code:**
> 
> ```lua
> local Table = {"a", "b", "c"};
> ```
> 
> **I have used ast.to_lua_source for turning the ast into a lua code** **The output i got:**
> 
> ```lua
> local Table = {
>     1 = "a",
>     2 = "b",
>     3 = "c",
> }
> ;
> ```
> 
> **What it should be:**
> 
> ```lua
> local Table = {
>     [1] = "a",
>     [2] = "b",
>     [3] = "c",
> }
> ;
> ```
> 
> **Used python code:**
> 
> ```python
> from luaparser import ast
> 
> src = """
> local Table = {"a", "b", "c"};
> """
> 
> tree = ast.parse(src)
> print(ast.to_lua_source(tree))
> ```
