### ISSUE TITLE
Ambiguous syntax detected

### ISSUE THREAD

**Issue by zumoshi** [boolangery/py-lua-parser#53]
Hi

I've failed to reproduce the syntax error described in Lua runtime for both simple cases e.g.
```lua
io.write
('A')
```
([IDE One result](https://ideone.com/DsuwdX))

and the example mentioned in the link in [this comment](https://github.com/boolangery/py-lua-parser/blob/17ae223e7be6af43edb0ef124034659e57205cfc/luaparser/builder.py#L687):
```lua
z = (function(...) print(...); return "Bar"; end)
("Foo"):sub(1,1)

io.write(z)
```
([IDE One result](https://ideone.com/S9gI4F))

They work fine in both the online [Lua playground](https://www.lua.org/cgi-bin/demo) and [IDE One](https://ideone.com/), but fail to parse with this library getting this error:
```
File "/home/.../site-packages/luaparser/builder.py", line 697, in parse_tail
    raise SyntaxException(
luaparser.builder.SyntaxException: (2,4): Error: Ambiguous syntax detected
```
Was this a limitation of older Lua versions or ...?

For context my use case was static analysis of an existing working code base, and I was forced to patch it to be able to get it parsed by this library which was not ideal.

Is there any chance this error can be removed with ambiguity solved the same way Lua itself does? or was there another reason for this to be added that I missed? I didn't find any other issues/pull requests referencing this error.

Thanks.
---
Edit: for the [test case](https://github.com/boolangery/py-lua-parser/blob/17ae223e7be6af43edb0ef124034659e57205cfc/luaparser/tests/test_statements.py#L538) used Lua runtime resolves it to as if there was no newline present
![image](https://github.com/boolangery/py-lua-parser/assets/4184939/b6d91ad4-8c0c-4b26-8b51-c97a157ce495)

**Comment by boolangery** [comment]
Fixed on master, will release a version soon
