### ISSUE TITLE
Output as a lua file?

### ISSUE THREAD

**Issue by byteofprash** [boolangery/py-lua-parser#8]
Hallo,

Thanks for this wonderful project.
While I can happily parse a Lua file to an ast, if there a way to store a modified AST to a lua file?
Sorry, if this was already done before. Could you please help me to figure a way to do this if possible?

Thanks

**Comment by boolangery** [comment]
Hello,

This is not yet available but i'm working on it. You will be the first tester

If you can, please checkout the project on this branch: https://github.com/boolangery/py-lua-parser/tree/feature/lua-output

And give it a try: https://github.com/boolangery/py-lua-parser/tree/feature/lua-output#rendering-lua-code

For now, comments are not rendered.
