### ISSUE TITLE
Cant walk the ast tree if lua file has semicolon(;) or repeat until loop and multiple args(...)

### ISSUE THREAD

**Issue by TimKaptan** [boolangery/py-lua-parser#9]
![Screenshot_9](https://user-images.githubusercontent.com/31308083/89187325-cdf61c80-d5a5-11ea-9558-85d477d0d6ee.png)

When i try to walk the ast tree of a lua file which has semicolon or repeat until loop or varargs, lib throws an exception.

**Comment by gstggsstt** [comment]
I fixed this problem with following code
``` python
import luaparser
from luaparser import ast
from luaparser import astnodes

# fix bug in luaparser
def visit_Varargs(self, node): pass
luaparser.utils.visitor._methods[('luaparser.ast.WalkVisitor', luaparser.astnodes.Varargs)] = visit_Varargs
def visit_Repeat(self, node):
    self._nodes.append(node)
    self.visit(node.body)
    self.visit(node.test)
luaparser.utils.visitor._methods[('luaparser.ast.WalkVisitor', luaparser.astnodes.Repeat)] = visit_Repeat
```

**Comment by clouds56** [comment]
Thanks for fixing. Is there any plan for release this?

**Comment by boolangery** [comment]
I just made a new release :) 
https://github.com/boolangery/py-lua-parser/releases/tag/3.0.0
